### ISSUE TITLE
How to calculate pose using LiDAR?

### ISSUE THREAD

**Issue by akawincent** [marek-simonik/record3d#101]
Hello Record3D Team,

Thank you for creating such an impressive app! I‘m a researcher that need to use your app to get camera pose then reconstruct 3D scene. I am very interested in the technical details behind how Record3D estimates the camera pose from LiDAR data.

Specifically, I would like to know:

- What methods or algorithms does Record3D use to compute camera pose from LiDAR data?
- Is the Generalized ICP (GICP) algorithm used for this purpose, or is there a different approach in place?

If possible, could you please share some insights into the techniques involved? Your guidance would be greatly appreciated!

Looking forward to your response!

Best regards,

**Comment by marek-simonik** [comment]
Hello,

thank you for using Record3D.

The [camera poses](https://developer.apple.com/documentation/arkit/arcamera/2866108-transform) are estimated by Apple's ARKit framework. Unfortunately, Apple does not disclose the details on how their pose estimation pipeline looks like.
