### ISSUE TITLE
Question about reoslution and FPS during usb streaming

### ISSUE THREAD

**Issue by CDchenlin** [marek-simonik/record3d#102]
Hi,

Thank you so much for your excellent work in helping us record RGB-D videos using an iPhone. However, I have some questions regarding the streaming resolution and FPS. I've noticed that in Apple's official presentation, the highest FPS is 30 with a resolution of 320x180. Meanwhile, your app can achieve up to 60 FPS with a resolution of 256x192. I'm curious about how the app manages to double the FPS, albeit with a slightly smaller resolution.

Sincerely,
Henry
![image](https://github.com/user-attachments/assets/0934a866-0a5e-470d-b6ef-5b090394927d)

**Comment by marek-simonik** [comment]
Hi,

thank you for using Record3D. What you showed in the screenshot, is a table which applies to the AVFoundation API as the method of accessing the LiDAR stream, which is limited to 30 FPS.

Aternatively, you can use the ARKit API to access the LiDAR data, which gives you 60 FPS, and this is the API used by Record3D.
