### ISSUE TITLE
The resolution of lidar RGBD images

### ISSUE THREAD

**Issue by CoWlTer** [marek-simonik/record3d#14]
Hi, thanks for sharing this repo. During my using the USB live RGBD streaming, I encoutered a problem that the resolution of the image shot by lidar camera is too small, while the resolution of FaceID is normal. I'm wondering if the resolution of the RGBD images could be changed?

**Comment by marek-simonik** [comment]
Hi,
thank you for using Record3D! Unfortunately, Apple does not currently provide higher resolution, but if that would change in the future, I would update the app.

**Comment by marek-simonik** [comment]
Starting with Record3D 1.8, you can get up to 1440x1920 px RGB images for LiDAR. More details here: https://github.com/marek-simonik/record3d/issues/34
