### ISSUE TITLE
RGB-D images

### ISSUE THREAD

**Issue by hetryn** [marek-simonik/record3d#19]
Hello, would like to find out how I can get RGB + D images instead of videos. Thank you

**Comment by marek-simonik** [comment]
Hello,
you can export your 3D Video into the `.r3d` format, unzip the `.r3d` file and inside, you will find RGB + D images. See [this answer](https://github.com/marek-simonik/record3d/issues/7#issuecomment-736573410) for an example of decoding the depth data.
