### ISSUE TITLE
Import r3d metadata into blender and convert to animation

### ISSUE THREAD

**Issue by jaeh** [marek-simonik/record3d#33]
Hi Marek :)

we are currently implementing a blender python script that imports a .r3d file and then automatically animates the currently selected object in blender based on the values in metadata.

the repository with our blend file, data.r3d and python script is here:
https://github.com/thesystemcollective/record3d-blender-import
( the python script is embedded into blender, changes to the .py file won't change the behaviour, it is just for easier copy pasting into different blend files)

i have a few questions that would help me with debugging:
1. am i right in assuming that the poses array is ordered like the following:
  [qw, qx, qy, qz, px, py, pz] where q is the quaternion and p is the position?
2. my rotation and positioning seems to be off, did you use different axis than blender does?

please note that, for privacy reasons, i removed all files except the metadata file from the r3d file, it works with a full r3d file too though.

**Comment by jaeh** [comment]
just found a bug with the r3d import, will fix that, the questions remain though.

**Comment by marek-simonik** [comment]
Hi Jascha!

The 7-element arrays contain elements in this order: [qx, qy, qz, qw, px, py, pz] (i.e. qw is *not* the first element in the array).

To answer your second question: Record3D uses the OpenGL coordinate system convention, which is different than the one Blender uses; see e.g. [this link](https://www.ranjithraghunathan.com/blender-coordinate-system-to-opengl/) for more details.

**Comment by jaeh** [comment]
thanks! this should be all i need to know, back to python :)

i might reopen this issue if i need more answers, hope that's fine.
