### ISSUE TITLE
How to get higher-resolution RGB images (1920 x 1440)?

### ISSUE THREAD

**Issue by andrewsonga** [marek-simonik/record3d#34]
Hello,

first of all, thank you so much for your work. It has truly made extracting RGBD video from iphone / ipads a lot easier! 

I just wanted to ask whether it's possible to extract higher-resolution RGB images than the current max. resolution that is outputted by the app (960 x 720). I've been playing around with ARKit and it seems like the resolution of the capturedImage (RGB) is (1920 x 1440); is it possible to capture RGB video at this resolution (1920 x 1440) on record3d as well - either via the app itself, or via USB stream to a mac?

Thank you in advance :)

**Comment by marek-simonik** [comment]
Hello,

thank you for using Record3D :)! I had to lower the resolution to 720×960 px due to performance issues, but 1440×1920 px RGB images might come in a future update if I manage to improve the performance.

P.S. I might reply faster via email (support@record3d.app).

**Comment by marek-simonik** [comment]
The option to record 1440x1920 px RGB images for LiDAR has been added in Record3D 1.8. To enable this option, navigate to the Settings tab and turn on "Higher-quality LiDAR recording".
