### ISSUE TITLE
Hi, Question about intrinsics.

### ISSUE THREAD

**Issue by HeoJinLareine** [marek-simonik/record3d#37]
If I scale up depthMap image size 4 times, correct intrinsic matrix is multipling x4 for each component for "intrinsic_mat = self.get_intrinsic_mat_from_coeffs(self.session.get_intrinsic_mat())"?

**Comment by marek-simonik** [comment]
It should be enough to multiply the 4 intrinsic coefficients by the scale factor (i.e. by 4, as you wrote) and construct the intrinsic matrix from those 4 scaled coefficients.
