### ISSUE TITLE
Install error for Record3D python package for Win1, Python 3.10

### ISSUE THREAD

**Issue by qxray** [marek-simonik/record3d#47]
During installation of the latest revision for Record3D python streaming I get an error when compiling Record3DStream.cpp:
[...]\record3d\python-bindings\pybind11\include\pybind11\cast.h(442,36): error C2027: use of undefined type '_frame' 
[[...]\record3d\build\temp.win-amd64-cpython-311\Release\record3d_py.vcxproj]
C:\Python\Python311\include\pytypedefs.h(22): message : see declaration of '_frame' [C[...]\record3d\build\temp.win-am
d64-cpython-311\Release\record3d_py.vcxproj]

Any hints what could be the reason?

**Comment by marek-simonik** [comment]
I assume you were eventually able to get the Python demo to work after I updated `pybind11` and uploaded a new Windows pip package. Feel free to reopen this issue if you still experience the same error.
