### ISSUE TITLE
Launch start stream command from terminal

### ISSUE THREAD

**Issue by mattiazuffanelli** [marek-simonik/record3d#49]
Hi, 
I need to open the app and run the stream command from the terminal (iphone 13pro wired connected to my mac). 
Is there something  in the library (command/examples) I could use?

Thanks a lot,
Mattia

**Comment by marek-simonik** [comment]
This issue has been inactive for some time, so I'm assuming you were able to get the demo running. Feel free to reopen this issue if you need help.
