### ISSUE TITLE
Problem when trying to install record3d package

### ISSUE THREAD

**Issue by xuewang1997** [marek-simonik/record3d#51]
### Hi, I'm trying to install the newest version 3.1.1 of Record3d package using pip. However, I got this error message: 
Collecting record3d
  Using cached record3d-1.3.1-1.tar.gz (539 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/bd/ef/9f785310e900e88cc01d98443bec956c8bda1901a099642dae68db5c9f8b/record3d-1.3.1-1.tar.gz (from https://pypi.org/simple/record3d/): Requested record3d from https://files.pythonhosted.org/packages/bd/ef/9f785310e900e88cc01d98443bec956c8bda1901a099642dae68db5c9f8b/record3d-1.3.1-1.tar.gz has inconsistent version: expected '1.3.1.post1', but metadata has '1.3.1'
  Using cached record3d-1.3.0-cp310-cp310-macosx_10_15_x86_64.whl
Requirement already satisfied: numpy in ./opt/miniconda3/envs/LipMotion/lib/python3.10/site-packages (from record3d) (1.23.5)
Installing collected packages: record3d
Successfully installed record3d-1.3.0

### Thank you so much!

**Comment by marek-simonik** [comment]
I uploaded a new version of the `record3d` module to PyPI (the only difference is change of the release version string from `1.3.1` to `1.3.1.post2`).

Please try to install `record3d` via `pip` again. In case of emergency, you can install directly from the source code, as mentioned in the Readme:

```bash
git clone https://github.com/marek-simonik/record3d
cd record3d
python setup.py install
```

Please let me know if it was possible to install `record3d` via `pip` now. Thanks.
