### ISSUE TITLE
Why does the point cloud reconstruction of the depth map sequence I export have bad effect?

### ISSUE THREAD

**Issue by wahiahia** [marek-simonik/record3d#53]
Is it because I need other ways to obtain depth map？

**Comment by wahiahia** [comment]
Is it because I need other ways to obtain depth map

**Comment by marek-simonik** [comment]
I'm not sure if I understood your question. What do you mean by bad effect and what do you wish to do?

**Comment by wahiahia** [comment]
I want to use depth frames for research related to 3D reconstruction. When I exported data directly to Mac through the Record3d app, I get .Exr files, but I want to use PNG format files, I convert EXR to PNG directly through Mac conversion, and I find that the data I get is lost. So is it possible to get a depth frame that can only be transmitted through the USB in this project?

**Comment by marek-simonik** [comment]
> So is it possible to get a depth frame that can only be transmitted through the USB in this project?

Do you mean if it is possible to have Record3D export raw, uncompressed `float32` bytes as depth data? That is not possible.

However, the EXR files contain `float32` depth values (in meters) in the Red channel. I assume Mac conversion is unable to read/convert 32-bit `float32` values into 8-bit `uint8` PNG files, so you will have to convert the depth data in a different way, i.e. reading the `float32` values from EXR yourself and performing the conversion into PNG yourself too.
