### ISSUE TITLE
Decode depth value from RGBD video

### ISSUE THREAD

**Issue by pablodawson** [marek-simonik/record3d#70]
Hey, I'm having trouble decoding the depth values from the exported RGBD video.
I need the raw (not color mapped) values to make meshes. Is this possible?

**Comment by marek-simonik** [comment]
Hi,
yes, that's possible — check out [the description of the RGBD video format](https://github.com/marek-simonik/record3d-simple-wifi-streaming-demo#22-rgbd-video-format) and [the Three.js demo](https://github.com/marek-simonik/record3d-wifi-streaming-and-rgbd-mp4-3d-video-demo) that let's you render meshes.
