### ISSUE TITLE
Camera position from frontal camera

### ISSUE THREAD

**Issue by yorard123** [marek-simonik/record3d#74]
Hi, 

I would like to know if is it expected that the camera position from the frontal camera is not given. I always get the same values: Camera pose: qx: 0.0, qy: 0.0, qz: 0.0, qw: 1.0, tx: 0.0, ty: 0.0, tz: 0.0
It seems to work for the rear camera. I am streaming via usb with an iphone 13 pro.

Thanks!!

**Comment by marek-simonik** [comment]
Hi,
unfortunately, this is the expected result. Apple does not provide pose data for the selfie FaceID camera like it does for LiDAR, so that is the reason why I put the identity pose for each frame captured by the selfie FaceID camera.
