### ISSUE TITLE
Cannot flip camera

### ISSUE THREAD

**Issue by gursi26** [marek-simonik/record3d#97]
There appears to be no option to flip the camera on the app? I am using an IPhone 14. Attached a screenshot of the app below.

![Screenshot 2024-10-18 at 13 55 58 jpeg](https://github.com/user-attachments/assets/9e2d20e2-f101-4d09-896d-7c6f7836bd48)

**Comment by marek-simonik** [comment]
Hello,

thanks for using Record3D. That is the expected behavior.

Record3D needs a "depth-sensing" camera to be able to record 3D videos. iPhone 14 (non-Pro) does not have LiDAR, which means you can only use the selfie FaceID camera for recording 3D videos, so there is no camera flip button.

**Comment by gursi26** [comment]
i see, thanks for clarifying
